
package codigo;


public enum Tokens {
    /*Lista de los Tokens que se pueden encontrar*/
    Entero,
    Real,
    Cadena,
    Boleano,
    Nulo,
    Si,
    Entonces,
    Sino,
    Devolver,
    Verdadero,
    Falso,
    Desde,
    Mientras,
    Incrementar,
    Decrementar,
    Hacer,
    Escribir,
    Clase,
    Extiende,
    Incluir,
    Propiedades,
    Metodos,
    Publicas,
    Privadas,
    Protegidas,
    Principal,
    Eliminar,
    Instanciar,
    Constructor,
    Destructor,
    Igual,
    Suma,
    Resta,
    Multiplicacion,
    Division,
    Modulo,
    Exponenciacion,
    Incremento,
    Decremento,
    Comparador,
    Diferente,
    MenorIgual,
    MayorIgual,
    Mayor,
    Menor,
    And,
    Or,
    DosPuntos,
    PuntoComa,
    ParentesisA,
    ParentesisC,
    CorcheteA,
    CorcheteC,
    LlaveA,
    LlaveC,
    Coma,
    Punto,
    Identificador,
    IdClase,
    NumEntero,
    NumReal,
    CadenaT,
    Tabulador,
    Comillas,
    Linea,
    
    ERROR
}
